# Generated by Django 3.1.6 on 2021-02-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='_for',
            field=models.CharField(choices=[('men', 'men'), ('women', 'women'), ('kids', 'kids')], max_length=200, null=True),
        ),
    ]
