# Generated by Django 3.1.6 on 2021-02-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category__for'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crousal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='Crousal Image')),
            ],
        ),
    ]
