# Generated by Django 3.1.6 on 2021-02-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_crousal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='type_of',
            new_name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='poster',
            field=models.ImageField(null=True, upload_to='Category Poster'),
        ),
    ]
