# Generated by Django 3.1.6 on 2021-02-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210216_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='metaTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
