# Generated by Django 3.1.6 on 2021-02-17 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Reviews',
        ),
    ]
