# Generated by Django 3.1.6 on 2021-02-17 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210217_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.available_for'),
        ),
    ]
