# Generated by Django 3.1.6 on 2021-02-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category__for'),
    ]

    operations = [
        migrations.AddField(
            model_name='available_for',
            name='img',
            field=models.ImageField(null=True, upload_to='Available For'),
        ),
    ]
