# Generated by Django 3.1.6 on 2021-02-18 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210217_1836'),
        ('products', '0009_available_for_img'),
    ]

    operations = [
    ]
