# Generated by Django 3.1.6 on 2021-02-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210218_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='large_size',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='medium_size',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='small_size',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='xl_size',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='xxl_size',
            field=models.BooleanField(null=True),
        ),
    ]
