# Generated by Django 3.1.6 on 2021-02-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210218_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large'), ('xlarge', 'xlarge'), ('2xlarge', '2xlarge')], max_length=100, null=True),
        ),
    ]
