# Generated by Django 3.1.6 on 2021-02-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20210220_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='code',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
