# Generated by Django 3.1.6 on 2021-03-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20210306_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_requested_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
