# Generated by Django 3.1.6 on 2021-03-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_order_refund_requested_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='track_order',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
