# Generated by Django 3.1.6 on 2021-03-29 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20210329_1116'),
        ('products', '0022_auto_20210316_2255'),
    ]

    operations = [
    ]
