# Generated by Django 3.1.6 on 2021-03-31 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_merge_20210330_1906'),
        ('products', '0027_auto_20210331_2025'),
    ]

    operations = [
    ]
