# Generated by Django 3.1.6 on 2021-04-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_item_thirty_four_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
            ],
        ),
    ]
